[options]
; This is the password that allows database operations:
admin_passwd = 12345
db_host = localhost
db_port = 5432
db_user = odoo18
db_password = odoo18
db_template = template1
db_name = odoo18_module_development
dbfilter = ^odoo18_module_development$
list_db = False
data_dir = C:\odoo 18\odoo18\.odoo-data
addons_path = C:\odoo 18\odoo18\community\addons,C:\odoo 18\odoo18\custom-addons\ODOO18-MODULE-DEVELOPMENT\addons
default_productivity_apps = True
